правки  ci

diff --git a/.github/workflows/ui_tests.yml b/.github/workflows/ui_tests.yml
--- a/.github/workflows/ui_tests.yml
+++ b/.github/workflows/ui_tests.yml
@@ -10,8 +10,6 @@ permissions:
 jobs:
   run-ui-tests:
     runs-on: ubuntu-latest
-    name: Run UI Tests
-
     steps:
       - name: Checkout tests repository
         uses: actions/checkout@v4
@@ -26,7 +24,7 @@ jobs:
           curl -LsSf https://astral.sh/uv/install.sh | sh
           echo "$HOME/.cargo/bin" >> $GITHUB_PATH
 
-      - name: Install dependencies with uv
+      - name: Install dependencies
         run: |
           uv pip install --system -r requirements.txt
 
@@ -45,8 +43,6 @@ jobs:
   generate-report:
     runs-on: ubuntu-latest
     needs: [ run-ui-tests ]
-    name: Generate Report
-
     steps:
       - uses: actions/setup-java@v3
         with:
@@ -69,14 +65,20 @@ jobs:
         run: |
           mkdir -p _site/ui
           allure generate allure-results-ui -o _site/ui --clean
-          # Фикс путей для GitHub Pages
-          find _site/ui -type f -name "*.html" -exec sed -i 's|/static/|./static/|g' {} \;
-          find _site/ui -type f -name "*.js" -exec sed -i 's|/static/|./static/|g' {} \;
+          
+          find _site/ui -type f \( -name '*.html' -o -name '*.js' \) -exec sed -i 's|/static/|./static/|g' {} \;
+          echo '<base href="/SimbirsoftTask/ui/">' >> _site/ui/index.html
 
       - name: Add .nojekyll file
         run: |
           touch _site/.nojekyll
           echo "Disabled Jekyll processing" > _site/.nojekyll
+
+      - name: Verify report structure
+        run: |
+          echo "Generated files:"
+          ls -laR _site/ui
+          [ -f "_site/ui/index.html" ] || { echo "Error: index.html not found"; exit 1; }
 
       - name: Upload report artifact
         uses: actions/upload-artifact@v4
@@ -88,19 +90,12 @@ jobs:
   publish-report:
     runs-on: ubuntu-latest
     needs: generate-report
-    name: Publish Report
-
     steps:
       - name: Download report
         uses: actions/download-artifact@v4
         with:
           name: test-report
           path: _site
-
-      - name: Verify report structure
-        run: |
-          ls -laR _site
-          [ -f "_site/ui/index.html" ] || exit 1
 
       - name: Upload to GitHub Pages
         uses: actions/upload-pages-artifact@v3
